#include "graphics/colors.hpp"
#include "liblvgl/lvgl.h"

namespace graphics::colors{
        const lv_color_t RED =               lv_color_make(0xFF, 0x00, 0x00);
        const lv_color_t BLUE =              lv_color_make(0x00, 0x00, 0xFF);
        const lv_color_t LIME_GREEN =        lv_color_make(0x00, 0xFF, 0x00);
        const lv_color_t BLACK =             lv_color_make(0x00, 0x00, 0x00);
        const lv_color_t WHITE =             lv_color_make(0xFF, 0xFF, 0xFF);
        const lv_color_t DARK_GREY =         lv_color_make(0x3D, 0x3D, 0x3D);
        const lv_color_t LIGHT_GREY =        lv_color_make(0xBA, 0xBA, 0xBA);
        const lv_color_t YELLOW =            lv_color_make(0xFF, 0xFF, 0x00);
        const lv_color_t ORANGE =            lv_color_make(0xFF, 0xA5, 0x00);
        const lv_color_t MAGENTA =           lv_color_make(0xFF, 0x00, 0xDD);
        const lv_color_t CYAN =              lv_color_make(0x00, 0xFF, 0xFF);
        const lv_color_t PURPLE =            lv_color_make(0xB0, 0x00, 0xE0);
        const lv_color_t PINK =              lv_color_make(0xFE, 0xA4, 0xD4);
        const lv_color_t MAROON =            lv_color_make(0xA5, 0x2A, 0x2A);
        const lv_color_t OLIVE_GREEN =       lv_color_make(0x80, 0x80, 0x00);
        const lv_color_t NAVY_BLUE =         lv_color_make(0x00, 0x00, 0x5C);
        const lv_color_t TEAL =              lv_color_make(0x00, 0x80, 0x80);
        const lv_color_t SILVER =            lv_color_make(0xC0, 0xC0, 0xC0);
        const lv_color_t GOLD =              lv_color_make(0xBD, 0xA0, 0x00);
        const lv_color_t DARK_BROWN =        lv_color_make(0x5C, 0x36, 0x0F);
        const lv_color_t LIGHT_BROWN =       lv_color_make(0xC7, 0x85, 0x48);
        const lv_color_t BEIGE =             lv_color_make(0xA8, 0x95, 0x8A);
        const lv_color_t CORAL =             lv_color_make(0xFF, 0x7F, 0x50);
        const lv_color_t TURQUOISE =         lv_color_make(0x40, 0xE0, 0xD0);
        const lv_color_t LAVENDER =          lv_color_make(0xF9, 0xD2, 0xFE);
        const lv_color_t SALMON =            lv_color_make(0xFA, 0x80, 0x72);
        const lv_color_t KHAKI =             lv_color_make(0xF0, 0xE6, 0x8C);
        const lv_color_t MINT_GREEN =        lv_color_make(0x98, 0xFF, 0x98);
        const lv_color_t SKY_BLUE =          lv_color_make(0x90, 0xDF, 0xFE);
        const lv_color_t PEACH =             lv_color_make(0xFF, 0xDA, 0xB9);
        const lv_color_t ROSE =              lv_color_make(0xFF, 0x00, 0x7F);
        const lv_color_t CHARCOAL =          lv_color_make(0x33, 0x33, 0x33);
        const lv_color_t IVY_GREEN =         lv_color_make(0x00, 0x64, 0x00);
        const lv_color_t COBALT_GREEN =      lv_color_make(0x3D, 0x59, 0x5A);
        const lv_color_t COBALT =            lv_color_make(0x3D, 0x59, 0xAB);
        const lv_color_t SLATE_GREY =        lv_color_make(0x70, 0x80, 0x90);
        const lv_color_t IVORY =             lv_color_make(0xFF, 0xFF, 0xF0);
        const lv_color_t MAUVE =             lv_color_make(0xE0, 0xB0, 0xFF);
        const lv_color_t PLUM =              lv_color_make(0x8E, 0x3A, 0x58);
        const lv_color_t INDIGO =            lv_color_make(0x4B, 0x00, 0x82);
        const lv_color_t CERULEAN =          lv_color_make(0x00, 0x7B, 0xFF);
        const lv_color_t AMBER =             lv_color_make(0xFF, 0xBF, 0x00);
        const lv_color_t APRICOT =           lv_color_make(0xFB, 0xCE, 0xB1);
        const lv_color_t AQUAMARINE =        lv_color_make(0x7F, 0xFF, 0xD4);
        const lv_color_t CHARTREUSE =        lv_color_make(0x7F, 0xFF, 0x00);
        const lv_color_t FERN_GREEN =        lv_color_make(0x4F, 0x9A, 0x02);
        const lv_color_t PERIWINKLE =        lv_color_make(0xCC, 0x99, 0xFF);
        const lv_color_t SAPPHIRE =          lv_color_make(0x0F, 0x52, 0xFF);
        const lv_color_t SANGRIA =           lv_color_make(0x92, 0x00, 0x2C);
        const lv_color_t SEPia =             lv_color_make(0x70, 0x40, 0x20);
        const lv_color_t BABY_PINK =         lv_color_make(0xF4, 0xC2, 0xE7);
        const lv_color_t CELADON =           lv_color_make(0xAC, 0xE1, 0xAF);
        const lv_color_t CHARMANDER_ORANGE = lv_color_make(0xFF, 0x6F, 0x30);
        const lv_color_t ELECTRIC_LIME =     lv_color_make(0xCC, 0xFF, 0x00);
        const lv_color_t RASPBERRY =         lv_color_make(0xE3, 0x00, 0x7F);
        const lv_color_t COBALT_BLUE =       lv_color_make(0x00, 0x3D, 0xFF);
        const lv_color_t FOREST_GREEN =      lv_color_make(0x22, 0x8B, 0x22);
        const lv_color_t BRONZE =            lv_color_make(0xCD, 0x7F, 0x32);
        const lv_color_t COPPER =            lv_color_make(0xB0, 0x60, 0x30);
        const lv_color_t AZURE =             lv_color_make(0x00, 0x7F, 0xFF);
        const lv_color_t MAGENTA_PINK =      lv_color_make(0xFF, 0x0F, 0xA0);
        const lv_color_t SCARLET =           lv_color_make(0xFF, 0x14, 0x00);
        const lv_color_t CERULEAN_BLUE =     lv_color_make(0x2A, 0x52, 0xBE);
        const lv_color_t TIGER_ORANGE =      lv_color_make(0xFF, 0x7E, 0x00);
        const lv_color_t LIME_YELLOW =       lv_color_make(0xEE, 0xFF, 0x00);
        const lv_color_t HOT_PINK =          lv_color_make(0xFF, 0x69, 0xB4);
        const lv_color_t CERISE =            lv_color_make(0xDE, 0x31, 0x7A);
        const lv_color_t BLUSH_PINK =        lv_color_make(0xFF, 0x69, 0x91);
        const lv_color_t PEWTER =            lv_color_make(0x96, 0xA8, 0xA1);
        const lv_color_t SMOKE_GREY =        lv_color_make(0x74, 0x74, 0x74);
        const lv_color_t DOVE_GREY =         lv_color_make(0x70, 0x70, 0x70);
        const lv_color_t FLAME_ORANGE =      lv_color_make(0xE2, 0x4C, 0x00);
        const lv_color_t SUNSET_YELLOW =     lv_color_make(0xFF, 0xC0, 0x18);
        const lv_color_t PEAR_GREEN =        lv_color_make(0xD1, 0xE2, 0x6E);
        const lv_color_t ROYAL_BLUE =        lv_color_make(0x41, 0x69, 0xE1);
        const lv_color_t OCEAN_BLUE =        lv_color_make(0x4F, 0x42, 0xFF);
        const lv_color_t GRASS_GREEN =       lv_color_make(0x7C, 0xFC, 0x00);
        const lv_color_t CHOCOLATE_BROWN =   lv_color_make(0x7B, 0x3F, 0x00);
        const lv_color_t MOCHA =             lv_color_make(0xC4, 0x9A, 0x6C);
        const lv_color_t TAN =               lv_color_make(0xD2, 0xB4, 0x8C);
        const lv_color_t LEMON_YELLOW =      lv_color_make(0xFF, 0xFF, 0x66);
        const lv_color_t LILAC =             lv_color_make(0xC8, 0xA2, 0xC8);
        const lv_color_t MAHOGANY =          lv_color_make(0xC0, 0x40, 0x20);
        const lv_color_t SLATE_BLUE =        lv_color_make(0x6A, 0x5A, 0xCD);
        const lv_color_t BABY_YELLOW =       lv_color_make(0xFF, 0xFF, 0xB3);
        const lv_color_t MOSS_GREEN =        lv_color_make(0x8A, 0x9A, 0x5B);
        const lv_color_t STONE_GREY =        lv_color_make(0x8D, 0x92, 0x90);
        const lv_color_t ASPEN_GREEN =       lv_color_make(0x7C, 0xB4, 0x6A);
        const lv_color_t FOSSIL_GREY =       lv_color_make(0x9E, 0x9E, 0x9E);
        const lv_color_t WHEAT =             lv_color_make(0xF5, 0xDE, 0xB3);
        const lv_color_t CREAM =             lv_color_make(0xFF, 0xFD, 0xD5);
        const lv_color_t PEANUT_BROWN =      lv_color_make(0xA3, 0x6B, 0x00);
        const lv_color_t RUST =              lv_color_make(0xB7, 0x40, 0x20);
        const lv_color_t BRICK_RED =         lv_color_make(0xCB, 0x41, 0x26);
        const lv_color_t SANDY_BROWN =       lv_color_make(0xF4, 0xA4, 0x60);
        const lv_color_t OCHRE =             lv_color_make(0xCC, 0x77, 0x33);
        const lv_color_t JADE_GREEN =        lv_color_make(0x00, 0xA8, 0x6B);
        const lv_color_t PEACOCK_BLUE =      lv_color_make(0x33, 0x66, 0x99);
        const lv_color_t RUSTY_RED =         lv_color_make(0xDA, 0x2C, 0x43);
        const lv_color_t BRIGHT_PINK =       lv_color_make(0xFF, 0x00, 0x7A);
        const lv_color_t BRIGHT_PURPLE =     lv_color_make(0xBF, 0x00, 0xFF);
        const lv_color_t BRIGHT_TEAL =       lv_color_make(0x00, 0xFF, 0xCC);
        const lv_color_t BRIGHT_ORCHID =     lv_color_make(0xFF, 0x39, 0xB5);
        const lv_color_t BRIGHT_TURQUOISE =  lv_color_make(0x30, 0xD5, 0xC8);
        const lv_color_t BRIGHT_CORAL =      lv_color_make(0xFF, 0x5E, 0x6C);
        const lv_color_t BRIGHT_AMBER =      lv_color_make(0xFF, 0xBF, 0x00);
        const lv_color_t BRIGHT_COPPER =     lv_color_make(0xDA, 0x8A, 0x67);
        const lv_color_t BRIGHT_BRONZE =     lv_color_make(0xFF, 0xA5, 0x4F);
        const lv_color_t ELECTRIC_RED =      lv_color_make(0xFF, 0x33, 0x33);
        const lv_color_t ELECTRIC_ORANGE =   lv_color_make(0xFF, 0x66, 0x00);
        const lv_color_t ELECTRIC_PINK =     lv_color_make(0xFF, 0x20, 0x93);
        const lv_color_t ELECTRIC_PURPLE =   lv_color_make(0xBF, 0x00, 0xFF);
        const lv_color_t ELECTRIC_CYAN =     lv_color_make(0x00, 0xFF, 0xFF);
        const lv_color_t ELECTRIC_GREEN =    lv_color_make(0x00, 0xFF, 0x33);
        const lv_color_t ELECTRIC_INDIGO =   lv_color_make(0x6F, 0x00, 0xFF);
        const lv_color_t ELECTRIC_VIOLET =   lv_color_make(0x8F, 0x00, 0xFF);
        const lv_color_t ELECTRIC_AQUA =     lv_color_make(0x00, 0xFF, 0xFF);
        const lv_color_t ELECTRIC_ROSE =     lv_color_make(0xFF, 0x00, 0x6F);
        const lv_color_t ELECTRIC_AMBER =    lv_color_make(0xFF, 0x7E, 0x00);
        const lv_color_t ELECTRIC_CERULEAN = lv_color_make(0x00, 0x7F, 0xFF);
        const lv_color_t ELECTRIC_CHARTREUSE=lv_color_make(0x7F, 0xFF, 0x00);
        const lv_color_t ELECTRIC_FUCHSIA =  lv_color_make(0xFF, 0x00, 0xFF);
        const lv_color_t ELECTRIC_SAPPHIRE = lv_color_make(0x0F, 0x52, 0xFF);
        const lv_color_t ELECTRIC_EMERALD =  lv_color_make(0x01, 0xFF, 0x3C);
        const lv_color_t ELECTRIC_RUBY =     lv_color_make(0xE0, 0x00, 0x5A);
        const lv_color_t ELECTRIC_ONYX =     lv_color_make(0x1F, 0x1F, 0x1F);
        const lv_color_t ELECTRIC_COBALT =   lv_color_make(0x3D, 0x59, 0xFF);
        const lv_color_t ELECTRIC_MINT =     lv_color_make(0x98, 0xFF, 0x98);
        const lv_color_t ELECTRIC_LAVENDER = lv_color_make(0xF9, 0xD2, 0xFF);
        const lv_color_t ELECTRIC_SKY_BLUE = lv_color_make(0x90, 0xDF, 0xFF);
        const lv_color_t ELECTRIC_IVY =      lv_color_make(0x00, 0x64, 0x33);
        const lv_color_t ELECTRIC_JADE =     lv_color_make(0x00, 0xFF, 0x6B);
        const lv_color_t ELECTRIC_PEACOCK =  lv_color_make(0x33, 0x99, 0xFF);
        const lv_color_t ELECTRIC_GRASS =    lv_color_make(0x7C, 0xFF, 0x00);
        const lv_color_t ELECTRIC_CHOCOLATE= lv_color_make(0x7B, 0x3F, 0x00);
        const lv_color_t ELECTRIC_SALMON =   lv_color_make(0xFF, 0x80, 0x72);
        const lv_color_t ELECTRIC_CREAM =    lv_color_make(0xFF, 0xFD, 0xD5);
        const lv_color_t ELECTRIC_TAN =      lv_color_make(0xD2, 0xB4, 0x8C);
        const lv_color_t ELECTRIC_LILAC =    lv_color_make(0xC8, 0xA2, 0xFF);
        const lv_color_t ELECTRIC_MAHOGANY = lv_color_make(0xC0, 0x40, 0x40);
        const lv_color_t ELECTRIC_SLATE =    lv_color_make(0x6A, 0x5A, 0xFF);
        const lv_color_t ELECTRIC_MOSS =     lv_color_make(0x8A, 0xFF, 0x5B);
        const lv_color_t ELECTRIC_STONE =    lv_color_make(0x8D, 0x92, 0xFF);
        const lv_color_t ELECTRIC_WHEAT =    lv_color_make(0xF5, 0xDE, 0xFF);
        const lv_color_t ELECTRIC_KHAKI =    lv_color_make(0xFF, 0xE6, 0x8C);
        const lv_color_t ELECTRIC_PEACH =    lv_color_make(0xFF, 0xDA, 0xB9);
        const lv_color_t ELECTRIC_ROSEWOOD = lv_color_make(0x65, 0x00, 0x5A);
        const lv_color_t ELECTRIC_CHARCOAL = lv_color_make(0x44, 0x44, 0x44);
        const lv_color_t ELECTRIC_YELLOW =   lv_color_make(0xFF, 0xFF, 0x00);
        const lv_color_t FUCHSIA =           lv_color_make(0xFF, 0x00, 0xFF);
        const lv_color_t EMERALD =           lv_color_make(0x01, 0xB2, 0x3C);
        const lv_color_t RUBY =              lv_color_make(0xE0, 0x00, 0x34);
        const lv_color_t ONYX_BLACK =        lv_color_make(0x0F, 0x0F, 0x0F);
        const lv_color_t CYBER_YELLOW =      lv_color_make(0xFF, 0xD3, 0x00);
        const lv_color_t ELECTRIC_BLUE =     lv_color_make(0x7D, 0xFF, 0xFF);
        const lv_color_t NEON_GREEN =        lv_color_make(0x39, 0xFF, 0x14);
        const lv_color_t BRIGHT_ORANGE =     lv_color_make(0xFF, 0x5A, 0x36);
        const lv_color_t DEEP_PURPLE =       lv_color_make(0x94, 0x00, 0xD3);
        const lv_color_t BRIGHT_RED =        lv_color_make(0xFF, 0x24, 0x00);
        const lv_color_t BRIGHT_BLUE =       lv_color_make(0x00, 0xBF, 0xFF);
        const lv_color_t BRIGHT_GREEN =      lv_color_make(0x66, 0xFF, 0x00);
        const lv_color_t BRIGHT_YELLOW =     lv_color_make(0xFF, 0xFF, 0x33);
        const lv_color_t BRIGHT_CYAN =       lv_color_make(0x00, 0xFF, 0xFF);
        const lv_color_t BRIGHT_MAGENTA =    lv_color_make(0xFF, 0x00, 0xFF);
        const lv_color_t BRIGHT_BROWN =      lv_color_make(0xA5, 0x2A, 0x2A);
        const lv_color_t BRIGHT_GREY =       lv_color_make(0xD3, 0xD3, 0xD3);
        const lv_color_t BRIGHT_NAVY =       lv_color_make(0x00, 0x00, 0x8B);
        const lv_color_t BRIGHT_OLIVE =      lv_color_make(0x80, 0x80, 0x20);
        const lv_color_t BRIGHT_MAROON =     lv_color_make(0xFF, 0x34, 0x52);
        const lv_color_t BRIGHT_BLACK =      lv_color_make(0x1A, 0x1A, 0x1A); //black but not black
        const lv_color_t BRIGHT_WHITE =      lv_color_make(0xFF, 0xFF, 0xFF); //you really think this is different?
        const lv_color_t TRANSPARENT =       lv_color_make(0x00, 0x00, 0x00); //also useless
        const lv_color_t LIGHT_TRANSPARENT = lv_color_make(0x80, 0x80, 0x80); //actually prolly useless
        const lv_color_t DARK_TRANSPARENT =  lv_color_make(0x40, 0x40, 0x40); //also prolly useless
        const lv_color_t SEMI_TRANSPARENT =  lv_color_make(0x20, 0x20, 0x20); //also also prolly useless
        const lv_color_t ULTRA_TRANSPARENT=  lv_color_make(0x10, 0x10, 0x10); //also also also prolly useless
        const lv_color_t INVISIBLE =         lv_color_make(0x00, 0x00, 0x00); //wtf gng
        const lv_color_t CLEAR =             lv_color_make(0x00, 0x00, 0x00); //stop
        const lv_color_t NONE =              lv_color_make(0x00, 0x00, 0x00); //please
        const lv_color_t NULL_COLOR =        lv_color_make(0x00, 0x00, 0x00); //im begging
        const lv_color_t ABSENT =            lv_color_make(0x00, 0x00, 0x00); //no more
        const lv_color_t NONEXISTENT =       lv_color_make(0x00, 0x00, 0x00); //ahhhhhh
        const lv_color_t UNDEFINED =         lv_color_make(0x00, 0x00, 0x00); //MAKE IT STOP
        const lv_color_t UNSEEN =            lv_color_make(0x00, 0x00, 0x00); //AAAAAAAAA
        const lv_color_t UNNOTICEABLE =      lv_color_make(0x00, 0x00, 0x00); //NOOOOOOOO
        const lv_color_t UNPERCEIVABLE =     lv_color_make(0x00, 0x00, 0x00); //WHY
        const lv_color_t UNOBSERVABLE =      lv_color_make(0x00, 0x00, 0x00); //JUST WHY
        const lv_color_t UNDETECTABLE =      lv_color_make(0x00, 0x00, 0x00); //I CAN'T TAKE IT ANYMORE
        const lv_color_t UNDISCERNIBLE =     lv_color_make(0x00, 0x00, 0x00); //PLEASE MAKE IT STOP
        const lv_color_t NONVISIBLE =        lv_color_make(0x00, 0x00, 0x00); //I GIVE UP
        const lv_color_t INCOGNITO =         lv_color_make(0x00, 0x00, 0x00); //I'm out
    }